# Agent
algorithm : "DQN"
EPISODES : 500

# Environment
environment : "TrafficEnv"
RENDER_MODE : "sumo"

# Run
DEVICE : cpu
SEED : 0
mode : "train"

#Hyperparameters
ALPHA : 0.001
GAMMA : 0.99
EPSILON : 1.0
EPSILON_DECAY : 0.995405
EPSILON_THRESHOLD: 0.1

#Save
PATH : "../algorithms/neural_networks/models/nm"
#Load
PATH_TEST : "../algorithms/neural_networks/models/nm/"
