# Agent
algorithm : "DQN"
EPISODES : 1500

# Environment
environment : "TrafficEnv"
RENDER_MODE : "sumo"

# Run
DEVICE : cuda
SEED : 0
mode : "train"

#Hyperparameters
ALPHA : 0.0008
GAMMA : 0.987
EPSILON : 1.0
EPSILON_DECAY : 0.9985
EPSILON_THRESHOLD: 0.1

#Save
PATH : "../algorithms/neural_networks/models"
#Load
PATH_TEST : "/home/sztaki/Documents/ICINCO_2024_rl_crossing-/algorithms/neural_networks/models/TrafficEnv_DQN_1712230824.5037785_4.pth"
